apiVersion: v1
data:
  ca.crt: '{{hub ( index ( lookup "v1"  "Secret" "sandbox" "root-secret").data "ca.crt" ) protect hub}}'
  tls.key: '{{hub ( index ( lookup "v1"  "Secret" "sandbox" "root-secret").data "tls.key" ) protect hub}}'
  tls.crt: '{{hub ( index ( lookup "v1"  "Secret" "sandbox" "root-secret").data "tls.crt" ) protect hub}}'
  
kind: Secret
metadata:
  annotations:
    cert-manager.io/alt-names: ""
    cert-manager.io/certificate-name: my-selfsigned-ca
    cert-manager.io/common-name: my-selfsigned-ca
    cert-manager.io/ip-sans: ""
    cert-manager.io/issuer-group: cert-manager.io
    cert-manager.io/issuer-kind: ClusterIssuer
    cert-manager.io/issuer-name: selfsigned-issuer
    cert-manager.io/uri-sans: ""
  name: root-secret
  namespace: sandbox
type: kubernetes.io/tls
